//
// AppClipDefaultExperienceUpdateRequestDataRelationships.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AppClipDefaultExperienceUpdateRequestDataRelationships: Sendable, Codable, JSONEncodable, Hashable {

    public var releaseWithAppStoreVersion: AppClipDefaultExperienceCreateRequestDataRelationshipsReleaseWithAppStoreVersion?

    public init(releaseWithAppStoreVersion: AppClipDefaultExperienceCreateRequestDataRelationshipsReleaseWithAppStoreVersion? = nil) {
        self.releaseWithAppStoreVersion = releaseWithAppStoreVersion
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case releaseWithAppStoreVersion
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(releaseWithAppStoreVersion, forKey: .releaseWithAppStoreVersion)
    }
}

