//
// AppClipDefaultExperienceAttributes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AppClipDefaultExperienceAttributes: Codable, JSONEncodable, Hashable {

    public var action: AppClipAction?

    public init(action: AppClipAction? = nil) {
        self.action = action
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case action
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(action, forKey: .action)
    }
}

