//
// AppEventCreateRequestDataRelationships.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AppEventCreateRequestDataRelationships: Codable, Hashable {

    public var app: AppCustomProductPageCreateRequestDataRelationshipsApp

    public init(app: AppCustomProductPageCreateRequestDataRelationshipsApp) {
        self.app = app
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case app
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(app, forKey: .app)
    }
}

