//
// AppPriceV2Relationships.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AppPriceV2Relationships: Codable, JSONEncodable, Hashable {

    public var appPricePoint: AppPriceV2RelationshipsAppPricePoint?
    public var territory: AppPricePointV2RelationshipsTerritory?

    public init(appPricePoint: AppPriceV2RelationshipsAppPricePoint? = nil, territory: AppPricePointV2RelationshipsTerritory? = nil) {
        self.appPricePoint = appPricePoint
        self.territory = territory
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case appPricePoint
        case territory
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(appPricePoint, forKey: .appPricePoint)
        try container.encodeIfPresent(territory, forKey: .territory)
    }
}

