//
// AppsBetaTesterUsagesV1MetricResponseDataInnerDimensions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AppsBetaTesterUsagesV1MetricResponseDataInnerDimensions: Sendable, Codable, JSONEncodable, Hashable {

    public var betaTesters: AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTesters?

    public init(betaTesters: AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTesters? = nil) {
        self.betaTesters = betaTesters
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case betaTesters
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(betaTesters, forKey: .betaTesters)
    }
}

