//
// AppsBetaTesterUsagesV1MetricResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AppsBetaTesterUsagesV1MetricResponse: Codable, JSONEncodable, Hashable {

    public var data: [AppsBetaTesterUsagesV1MetricResponseDataInner]
    public var links: PagedDocumentLinks
    public var meta: PagingInformation?
    public var included: [BetaTester]?

    public init(data: [AppsBetaTesterUsagesV1MetricResponseDataInner], links: PagedDocumentLinks, meta: PagingInformation? = nil, included: [BetaTester]? = nil) {
        self.data = data
        self.links = links
        self.meta = meta
        self.included = included
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case links
        case meta
        case included
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(data, forKey: .data)
        try container.encode(links, forKey: .links)
        try container.encodeIfPresent(meta, forKey: .meta)
        try container.encodeIfPresent(included, forKey: .included)
    }
}

