//
// AppStoreReviewAttachmentCreateRequestDataRelationships.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AppStoreReviewAttachmentCreateRequestDataRelationships: Codable, JSONEncodable, Hashable {

    public var appStoreReviewDetail: AppStoreReviewAttachmentCreateRequestDataRelationshipsAppStoreReviewDetail

    public init(appStoreReviewDetail: AppStoreReviewAttachmentCreateRequestDataRelationshipsAppStoreReviewDetail) {
        self.appStoreReviewDetail = appStoreReviewDetail
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case appStoreReviewDetail
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(appStoreReviewDetail, forKey: .appStoreReviewDetail)
    }
}

