//
// BetaTesterCreateRequestDataAttributes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BetaTesterCreateRequestDataAttributes: Codable, JSONEncodable, Hashable {

    public var firstName: String?
    public var lastName: String?
    public var email: String

    public init(firstName: String? = nil, lastName: String? = nil, email: String) {
        self.firstName = firstName
        self.lastName = lastName
        self.email = email
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case firstName
        case lastName
        case email
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(firstName, forKey: .firstName)
        try container.encodeIfPresent(lastName, forKey: .lastName)
        try container.encode(email, forKey: .email)
    }
}

