//
// BetaReviewState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum BetaReviewState: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case waitingForReview = "WAITING_FOR_REVIEW"
    case inReview = "IN_REVIEW"
    case rejected = "REJECTED"
    case approved = "APPROVED"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
