//
// BundleIdCapabilityCreateRequestDataAttributes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BundleIdCapabilityCreateRequestDataAttributes: Codable, JSONEncodable, Hashable {

    public var capabilityType: CapabilityType
    public var settings: [CapabilitySetting]?

    public init(capabilityType: CapabilityType, settings: [CapabilitySetting]? = nil) {
        self.capabilityType = capabilityType
        self.settings = settings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case capabilityType
        case settings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(capabilityType, forKey: .capabilityType)
        try container.encodeIfPresent(settings, forKey: .settings)
    }
}

