//
// CiTestStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum CiTestStatus: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case success = "SUCCESS"
    case failure = "FAILURE"
    case mixed = "MIXED"
    case skipped = "SKIPPED"
    case expectedFailure = "EXPECTED_FAILURE"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
