//
// CiWorkflowCreateRequestDataRelationships.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CiWorkflowCreateRequestDataRelationships: Codable, JSONEncodable, Hashable {

    public var product: CiWorkflowCreateRequestDataRelationshipsProduct
    public var repository: CiWorkflowCreateRequestDataRelationshipsRepository
    public var xcodeVersion: CiWorkflowCreateRequestDataRelationshipsXcodeVersion
    public var macOsVersion: CiWorkflowCreateRequestDataRelationshipsMacOsVersion

    public init(product: CiWorkflowCreateRequestDataRelationshipsProduct, repository: CiWorkflowCreateRequestDataRelationshipsRepository, xcodeVersion: CiWorkflowCreateRequestDataRelationshipsXcodeVersion, macOsVersion: CiWorkflowCreateRequestDataRelationshipsMacOsVersion) {
        self.product = product
        self.repository = repository
        self.xcodeVersion = xcodeVersion
        self.macOsVersion = macOsVersion
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case product
        case repository
        case xcodeVersion
        case macOsVersion
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(product, forKey: .product)
        try container.encode(repository, forKey: .repository)
        try container.encode(xcodeVersion, forKey: .xcodeVersion)
        try container.encode(macOsVersion, forKey: .macOsVersion)
    }
}

