//
// GameCenterMatchmakingAppRequestsV1MetricResponseDataInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GameCenterMatchmakingAppRequestsV1MetricResponseDataInner: Codable, JSONEncodable, Hashable {

    public enum Granularity: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case p1D = "P1D"
        case pt1h = "PT1H"
        case pt15m = "PT15M"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var dataPoints: GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDataPoints?
    public var dimensions: GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensions?
    public var granularity: Granularity?

    public init(dataPoints: GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDataPoints? = nil, dimensions: GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensions? = nil, granularity: Granularity? = nil) {
        self.dataPoints = dataPoints
        self.dimensions = dimensions
        self.granularity = granularity
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case dataPoints
        case dimensions
        case granularity
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(dataPoints, forKey: .dataPoints)
        try container.encodeIfPresent(dimensions, forKey: .dimensions)
        try container.encodeIfPresent(granularity, forKey: .granularity)
    }
}

