//
// GameCenterAppVersionRelationships.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GameCenterAppVersionRelationships: Codable, JSONEncodable, Hashable {

    public var compatibilityVersions: GameCenterAppVersionRelationshipsCompatibilityVersions?
    public var appStoreVersion: AppClipDefaultExperienceRelationshipsReleaseWithAppStoreVersion?

    public init(compatibilityVersions: GameCenterAppVersionRelationshipsCompatibilityVersions? = nil, appStoreVersion: AppClipDefaultExperienceRelationshipsReleaseWithAppStoreVersion? = nil) {
        self.compatibilityVersions = compatibilityVersions
        self.appStoreVersion = appStoreVersion
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case compatibilityVersions
        case appStoreVersion
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(compatibilityVersions, forKey: .compatibilityVersions)
        try container.encodeIfPresent(appStoreVersion, forKey: .appStoreVersion)
    }
}

