//
// GameCenterLeaderboardLocalizationRelationships.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GameCenterLeaderboardLocalizationRelationships: Codable, JSONEncodable, Hashable {

    public var gameCenterLeaderboard: GameCenterDetailRelationshipsDefaultLeaderboard?
    public var gameCenterLeaderboardImage: GameCenterLeaderboardLocalizationRelationshipsGameCenterLeaderboardImage?

    public init(gameCenterLeaderboard: GameCenterDetailRelationshipsDefaultLeaderboard? = nil, gameCenterLeaderboardImage: GameCenterLeaderboardLocalizationRelationshipsGameCenterLeaderboardImage? = nil) {
        self.gameCenterLeaderboard = gameCenterLeaderboard
        self.gameCenterLeaderboardImage = gameCenterLeaderboardImage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case gameCenterLeaderboard
        case gameCenterLeaderboardImage
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(gameCenterLeaderboard, forKey: .gameCenterLeaderboard)
        try container.encodeIfPresent(gameCenterLeaderboardImage, forKey: .gameCenterLeaderboardImage)
    }
}

