//
// PreviewFrameImage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PreviewFrameImage: Codable, JSONEncodable, Hashable {

    public var image: ImageAsset?
    public var state: AppMediaPreviewFrameImageState?

    public init(image: ImageAsset? = nil, state: AppMediaPreviewFrameImageState? = nil) {
        self.image = image
        self.state = state
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case image
        case state
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(image, forKey: .image)
        try container.encodeIfPresent(state, forKey: .state)
    }
}

