//
// SubscriptionPromotionalOfferUpdateRequestDataRelationships.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SubscriptionPromotionalOfferUpdateRequestDataRelationships: Sendable, Codable, JSONEncodable, Hashable {

    public var prices: SubscriptionPromotionalOfferInlineCreateRelationshipsPrices?

    public init(prices: SubscriptionPromotionalOfferInlineCreateRelationshipsPrices? = nil) {
        self.prices = prices
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case prices
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(prices, forKey: .prices)
    }
}

