//
// SubscriptionOfferCodeCustomCodeCreateRequestDataAttributes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SubscriptionOfferCodeCustomCodeCreateRequestDataAttributes: Codable, JSONEncodable, Hashable {

    public var customCode: String
    public var numberOfCodes: Int
    public var expirationDate: Date?

    public init(customCode: String, numberOfCodes: Int, expirationDate: Date? = nil) {
        self.customCode = customCode
        self.numberOfCodes = numberOfCodes
        self.expirationDate = expirationDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case customCode
        case numberOfCodes
        case expirationDate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(customCode, forKey: .customCode)
        try container.encode(numberOfCodes, forKey: .numberOfCodes)
        try container.encodeIfPresent(expirationDate, forKey: .expirationDate)
    }
}

