//
// AppStoreVersionPromotionsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class AppStoreVersionPromotionsAPI {

    /**

     - parameter appStoreVersionPromotionCreateRequest: (body) AppStoreVersionPromotion representation 
     - returns: AppStoreVersionPromotionResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func appStoreVersionPromotionsCreateInstance(appStoreVersionPromotionCreateRequest: AppStoreVersionPromotionCreateRequest) async throws -> AppStoreVersionPromotionResponse {
        var requestTask: RequestTask?
        return try await withTaskCancellationHandler {
            try Task.checkCancellation()
            return try await withCheckedThrowingContinuation { continuation in
                guard !Task.isCancelled else {
                  continuation.resume(throwing: CancellationError())
                  return
                }

                requestTask = appStoreVersionPromotionsCreateInstanceWithRequestBuilder(appStoreVersionPromotionCreateRequest: appStoreVersionPromotionCreateRequest).execute { result in
                    switch result {
                    case let .success(response):
                        continuation.resume(returning: response.body)
                    case let .failure(error):
                        continuation.resume(throwing: error)
                    }
                }
            }
        } onCancel: { [requestTask] in
            requestTask?.cancel()
        }
    }

    /**
     - parameter urlString: next or first url from App Store Connect API
     - returns: AppStoreVersionPromotionResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func appStoreVersionPromotionsCreateInstance(urlString: String) async throws -> AppStoreVersionPromotionResponse {
        var requestTask: RequestTask?
        return try await withTaskCancellationHandler {
            try Task.checkCancellation()
            return try await withCheckedThrowingContinuation { continuation in
                guard !Task.isCancelled else {
                  continuation.resume(throwing: CancellationError())
                  return
                }

                requestTask = appStoreVersionPromotionsCreateInstanceWithRequestBuilder(urlString: urlString).execute { result in
                    switch result {
                    case let .success(response):
                        continuation.resume(returning: response.body)
                    case let .failure(error):
                        continuation.resume(throwing: error)
                    }
                }
            }
        } onCancel: { [requestTask] in
            requestTask?.cancel()
        }
    }

    /**
     - POST /v1/appStoreVersionPromotions
     - BASIC:
       - type: http
       - name: itc-bearer-token
     - parameter appStoreVersionPromotionCreateRequest: (body) AppStoreVersionPromotion representation 
     - returns: RequestBuilder<AppStoreVersionPromotionResponse> 
     */
    open class func appStoreVersionPromotionsCreateInstanceWithRequestBuilder(appStoreVersionPromotionCreateRequest: AppStoreVersionPromotionCreateRequest) -> RequestBuilder<AppStoreVersionPromotionResponse> {
        let localVariablePath = "/v1/appStoreVersionPromotions"
        let localVariableURLString = ASCAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: appStoreVersionPromotionCreateRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AppStoreVersionPromotionResponse>.Type = ASCAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     - POST /v1/appStoreVersionPromotions
     - BASIC:
       - type: http
       - name: itc-bearer-token
     - parameter urlString: next or first url from App Store Connect API
     - returns: RequestBuilder<AppStoreVersionPromotionResponse> 
     */
    open class func appStoreVersionPromotionsCreateInstanceWithRequestBuilder(urlString: String) -> RequestBuilder<AppStoreVersionPromotionResponse> {
        let localVariableRequestBuilder: RequestBuilder<AppStoreVersionPromotionResponse>.Type = ASCAPI.requestBuilderFactory.getBuilder()
        return localVariableRequestBuilder.init(method: "POST", URLString: urlString, parameters: nil)
    }
}
